# Generated by Django 3.1.14 on 2022-12-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
