# Generated by Django 3.1.14 on 2022-12-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSection',
            fields=[
                ('board_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boards.board')),
                ('title', models.CharField(max_length=50)),
                ('max_issues_limit', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_sections', to='boards.board')),
            ],
            options={
                'verbose_name': 'Board Section',
                'verbose_name_plural': 'Board Sections',
            },
            bases=('boards.board',),
        ),
    ]
